<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>AgentBattle.SiteGenerator</RootNamespace>
    <AssemblyName>AgentBattle.SiteGenerator</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AgentBattle.Domain\AgentBattle.Domain.csproj" />
    <ProjectReference Include="..\AgentBattle.Web.Core\AgentBattle.Web.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

</Project>
