<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AgentBattle.Domain\AgentBattle.Domain.csproj" />
    <ProjectReference Include="..\AgentBattle.Web.Core\AgentBattle.Web.Core.csproj" />
  </ItemGroup>

</Project>
